spring:
    liquibase:
        enabled: false
        change-log: classpath:db/changelog/changelog-master.xml
    datasource:
        url: jdbc:mariadb://localhost:3306/night_life
        username: root
        password: thanatos
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                jdbc:
                connection:
                    driver_class: com.example.workflow.global.config.MySQL5InnoDBDialectEx
                dialect: org.hibernate.dialect.MariaDBDialect
        open-in-view: false
server:
    port: 8081
